
services:
    db:
      container_name: db
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: "userName"
        POSTGRES_PASSWORD: "TestPass123"
        POSTGRES_DB: "dbName"
        PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - "5432:5432"
      volumes:
        - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
        
    web:
        build: .
        ports:
            - "8080:8080"
        restart: always
        depends_on:
            - db
